Fix OD_VDDC_CURVE parsing (#17, #18)
Looks like that /sys/class/drm/cardX/device/pp_od_clk_voltage kernel
interface that is reporting OD_VDDC_CURVE is changing format from
version to version, like before 5.5 or something it was like (note MHZ)

  0: 800MHZ, 800mV

then up to 5.8 (or 5.9?) it was like (note MHz, '@' and missing comma)

  0: 800MHz @ 800mV

and now on 5.10 (note no commas or '@')

  0: 800MHz 800mV

This plays catch up with all these variants, and now "accepts" all
formatting variants as valid, and warns about possible future ones.

diff --git a/amdgpu-clocks b/amdgpu-clocks
--- a/amdgpu-clocks
+++ b/amdgpu-clocks
@@ -40,8 +40,16 @@ function fill_mclks() {
 }
 
 function fill_vddccurve() {
-  echo "  VDDC Curve state $1: ${2}, ${4}"
-  VDDC_CURVE[${1}]="vc ${1} ${2%*M[Hh]z} ${4%*mV}"
+  if [ $# -eq 3 ]; then
+    echo "  VDDC Curve state $1: ${2} ${3}"
+    VDDC_CURVE[${1}]="vc ${1} ${2%*M[Hh]z} ${3%*mV}"
+  elif [ $# -eq 4 ]; then
+    echo "  VDDC Curve state $1: ${2} @ ${4}"
+    VDDC_CURVE[${1}]="vc ${1} ${2%*M[Hh]z} ${4%*mV}"
+  else
+    echo "ERROR: Can't parse '$@', did pp_od_clk_voltage API change again?"
+    exit 2
+  fi
 }
 
 function parse_states() {
