Restore initial state & other small improvements
- Now the script will write the initial OverDrive state
  (states before first run), to /tmp/amdgpu-custom-state.cardX.initial
  and provide optional 'restore' parameter that can be used to  apply
  this initial state back to the card
- check_ppfeaturemask will suggest better ppfeature mask
  (only enable bit 14 and leave the rest to defaults)
- parse_states will now show power limit in watts instead of microwatts

diff --git a/amdgpu-clocks b/amdgpu-clocks
--- a/amdgpu-clocks
+++ b/amdgpu-clocks
@@ -4,13 +4,18 @@ USER_STATES_PATH=${USER_STATES_PATH:-/etc/default/amdgpu-custom-state}
 SYS_PPFMASK=/sys/module/amdgpu/parameters/ppfeaturemask
 [ ! -r ${SYS_PPFMASK} ] && echo "Can't access ${SYS_PPFMASK}" && exit 2
 
+if [ "x$1" == "xrestore" ]; then
+  RESTORE=true
+fi
+
 function check_ppfeaturemask() {
-  CURRENT_INT10_MASK=$(cat ${SYS_PPFMASK})
+  CURRENT_HEX_MASK=$(printf '%#x' "$(( $(cat ${SYS_PPFMASK}) ))")
   # 0x4000 or 14th bit is one indicating if OverDrive has been enabled
-  OVERDRIVE_MASK=$(printf '%#x' "$(($CURRENT_INT10_MASK & 0x4000))")
+  OVERDRIVE_MASK=$(printf '%#x' "$(( CURRENT_HEX_MASK & 0x4000 ))")
   [ "x${OVERDRIVE_MASK}" == "x0x4000" ] && return 0
-  echo -n "In order to set custom amdgpu power states, boot the machine with "
-  echo -n "amdgpu.ppfeaturemask=0xfffd7fff or amdgpu.ppfeaturemask=0xffffffff "
+  WANTED_MASK=$(printf '%#x' "$(( CURRENT_HEX_MASK | 0x4000 ))")
+  echo -n "In order to set custom amdgpu power states, enable OverDrive by "
+  echo -n "booting the machine with amdgpu.ppfeaturemask=${WANTED_MASK} "
   echo    "kernel option" && exit 2
 }
 
@@ -83,7 +88,8 @@ function parse_states() {
         FORCE_MCLK=${LINE#* }
         ;;
       "FORCE_POWER_CAP: "[0-9]*)
-        echo "  Force power cap to ${LINE#* }"
+        MICROWATTS=${LINE#* }
+        echo "  Force power cap to ${MICROWATTS%*000000}W"
         FORCE_POWER_CAP=${LINE#* }
         ;;
       "FORCE_PERF_LEVEL: "[a-z]*)
@@ -137,9 +143,32 @@ function set_custom_states() {
   fi
 }
 
+function backup_states() {
+  if [ ! -r ${BACKUP_STATE_FILE} ]; then
+    cp ${SYS_PP_OD_CLK} ${BACKUP_STATE_FILE}
+    echo "FORCE_PERF_LEVEL: $(cat ${PWR_LEVEL})" >> ${BACKUP_STATE_FILE}
+    echo "FORCE_POWER_CAP: $(cat ${PWR_CAP_FILE})" >> ${BACKUP_STATE_FILE}
+    echo "FORCE_POWER_PROFILE: 0" >> ${BACKUP_STATE_FILE}
+    echo "Writen initial backup states to ${BACKUP_STATE_FILE}"
+  else
+    echo "Won't write initial state to ${BACKUP_STATE_FILE}, it already exists."
+  fi
+}
+
+function restore_states() {
+  if [ -f ${BACKUP_STATE_FILE} ]; then
+    echo "Restoring all states to the initial defaults from ${BACKUP_STATE_FILE}"
+    USER_STATE_FILE=${BACKUP_STATE_FILE}
+  else
+    echo "Cant't access initial defaults at ${BACKUP_STATE_FILE}, aborting."
+    exit 2
+  fi
+}
+
 check_ppfeaturemask
 
 for USER_STATE_FILE in $(ls -1 ${USER_STATES_PATH}*.card*); do
+  BACKUP_STATE_FILE=/tmp/${USER_STATE_FILE##*/}.initial
   SYS_PP_OD_CLK=/sys/class/drm/${USER_STATE_FILE##*.}/device/pp_od_clk_voltage
   PWR_LEVEL=/sys/class/drm/${USER_STATE_FILE##*.}/device/power_dpm_force_performance_level
   PWR_PROFILE=/sys/class/drm/${USER_STATE_FILE##*.}/device/pp_power_profile_mode
@@ -149,13 +178,18 @@ for USER_STATE_FILE in $(ls -1 ${USER_STATES_PATH}*.card*); do
   HWMON_ID=$(ls -1 /sys/class/drm/${USER_STATE_FILE##*.}/device/hwmon)
   PWR_CAP_FILE=/sys/class/drm/${USER_STATE_FILE##*.}/device/hwmon/${HWMON_ID}/power1_cap
   if [ -f ${SYS_PP_OD_CLK} ]; then
+    if [ "x${RESTORE}" == "xtrue" ]; then
+      restore_states
+    else
+      backup_states
+    fi
     echo "Detecting the state values at ${SYS_PP_OD_CLK}:"
     parse_states ${SYS_PP_OD_CLK}
     echo "Verifying user state values at ${USER_STATE_FILE}:"
     parse_states ${USER_STATE_FILE}
     echo "Committing custom states to ${SYS_PP_OD_CLK}:"
-    echo "  Done"
     set_custom_states
+    echo "  Done"
   else
     echo "WARNING: ${SYS_PP_OD_CLK} does not exist, skipping!"
   fi
